GET http://localhost:3001/api/notes
###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "many many same true true",
    "important": true
}
###
PUT http://localhost:3001/api/notes/3 HTTP/1.1
content-type: application/json

{
    "content": "updated note content",
    "important": false
}
###
GET http://localhost:3001/api/notes/10
###
GET http://localhost:3001/info
###
DELETE  http://localhost:3001/api/persons/697aaa94b8058ee0560cf21e
###
GET http://localhost:3001/api/persons
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Jdpd0fsddddkdddkk sd",
    "number": "1-6s4ss94k4sddd-dl392io3kdl7890"
}
###
GET http://localhost:3001/api/persons/invalidid
###
DELETE http://localhost:3001/api/persons/697ab5c18905426a2ef33428